export { users, usersRelations } from './users.schema'
export { artists, artistsRelations } from './artists.schema'
export { collectionArtists, collectionArtistsRelations } from './collectionArtists.schema'

export { collections, collectionsRelations } from './collections.schema'
export { tracks, tracksRelations } from './tracks.schema'
export { tags, tagsRelations } from './tags.schema'
export { artistTags, artistTagsRelations } from './artistTags.schema'
export { collectionAdmins, collectionAdminsRelations } from './collectionAdmins.schema'
export { trackArtists, trackArtistsRelations } from './trackArtists.schema'
export { collectionTags, collectionTagsRelations } from './collectionTags.schema'
export { trackTags, trackTagsRelations } from './trackTags.schema'
export { artistAdmins, artistAdminsRelations } from './artistAdmins.schema'
export { trackAdmins, trackAdminsRelations } from './trackAdmins.schema'
