name: Build and Test

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [21.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test:unit
